### PR TITLE
initial support for all in orderbook for poloniex

### PR DESCRIPTION
**Pull request by gam-phon**
What do you think of the changes?
poloniex_wrapper.go is not working right now due to the changes in the struct. I will fix it later if you are willing to accept the feature.

### CODE REVIEW

**Comment by thrasher-** [comment]
Thank you!

**Comment by thrasher-** [comment]
As you stated, the last thing is to fix poloniex_wrapper.go, I can do this if you would like.

**Comment by gam-phon** [comment]
@thrasher- Thanks, I would appreciate it

**Comment by thrasher-** [comment]
Added in 5081a4b0c56354b1910d18c181cda66504bff2d7. Thanks!

**Pull request closed without merging**
