### PR TITLE
Add missing close file and missing stop ticker

### PR DESCRIPTION
**Pull request by leilaes**
# Description
Add missing close file and missing stop ticker.

Add [tenets](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/effective-go/defer-close-file/codelingo.yaml) to your [codelingo.yaml file](https://github.com/leilaes/gocryptotrader/blob/missing-closeFile-stopTicker/codelingo.yaml) to catch these issues during code review.

## Type of change

- [x] Code quality

# How Has This Been Tested?

`go test -race -coverprofile=coverage.txt -covermode=atomic  ./...`. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Existing unit tests pass locally and on Travis with my changes

### CODE REVIEW

**Comment by thrasher-** [comment]
Thanks @leilaes! This looks G2G once the linter issues have been resolved.

**Comment by leilaes** [comment]
@thrasher- Updated :)

**Comment by thrasher-** [comment]
Thanks @leilaes, just requires a rebase now.

**Comment by leilaes** [comment]
@thrasher- Done :)

**Pull request merged**
