### PR TITLE
Configurable webui port

### PR DESCRIPTION
**Pull request by crackcomm**
Web user interface port configurable by `PORT` environment variable.

### CODE REVIEW

**Comment by crackcomm** [comment]
@thrasher- oops something broke, I guess you just can edit it yourself, it's pretty useful when you're not root.

**Comment by thrasher-** [comment]
Thanks! Since PORT might already be set on a users env I think changing it to GCT_WEB_PORT will be better. I'll cherry-pick and amend the commit.

**Comment by thrasher-** [comment]
https://github.com/thrasher-/gocryptotrader/commit/f8b765fd53bc7b3f53a86df9fb2a2d4c6ff7eabc

**Comment by crackcomm** [comment]
Thanks

**Pull request closed without merging**
