### PR TITLE
Binance websocket

### PR DESCRIPTION
**Pull request by ermalguni**

### CODE REVIEW

**Comment by thrasher-** [comment]
Awesome work @ermalguni!

Regarding commit: https://github.com/thrasher-/gocryptotrader/pull/143/commits/4bb2e5da452366aef84ea549a2b1a22e0c66abde 

This breaks Travis and people who haven't setup a custom gocryptotrader directory. It would be best to revert this.

**Comment by ermalguni** [comment]
@thrasher- thanks. Will revert the commit then and update the PR.

**Comment by ermalguni** [comment]
@thrasher- reverted the imports. It seems that there is still sth weird going on though.

**Comment by thrasher-** [comment]
Thanks @ermalguni!

**Pull request merged**
