### PR TITLE
OKEX websocket

### PR DESCRIPTION
**Pull request by ermalguni**

### CODE REVIEW

**Comment by shazbert** [comment]
tACK - This is great, thanks for the PR!

**Comment by thrasher-** [comment]
Great stuff Ermal! 👍 Just had one nit and requires a rebase. Please let me know if you need any help with making the requested amendment.

**Comment by ermalguni** [comment]
@thrasher- Yes, help is needed :). Do you mean this: https://blog.github.com/2016-09-26-rebase-and-merge-pull-requests/?

**Comment by shazbert** [comment]
@ermalguni I think since you are on master:
```
git fetch
git rebase origin master // fix conflicts
git commit 
git push ermalguni --force 
```

**Comment by ermalguni** [comment]
@thrasher- thanks. Done.

**Comment by shazbert** [comment]
@ermalguni Thanks!

**Pull request merged**
