### PR TITLE
More refactoring on main()

### PR DESCRIPTION
**Pull request by lukekhamilton**
# Description

* Finished refactor on main() now it's much easier to quickly get a feel for what's happening on boot. 
* Minor updates to the makefile (non-breaking)

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [X] Tech Debit 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

make test, make

# Checklist:

- [X ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool 
- [ N] My changes generate no new warnings
- [n/a ] I have added tests that prove my fix is effective or that my feature works
- [ Y] New and existing unit tests pass locally and on Travis with my changes
- [ n/a] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lukekhamilton** [comment]
This build is failing due to an http request...

**Comment by dfischer** [comment]
Honestly, I find this harder to read.

http://number-none.com/blow/john_carmack_on_inlined_code.html

**Comment by thrasher-** [comment]
Thank you for submitting this PR @lukekhamilton! Engine will be drastically changing a lot of how the bot starts up and is more modular, which I hope to have merged in ASAP after QA is done:

https://github.com/thrasher-/gocryptotrader/blob/engine/main.go
https://github.com/thrasher-/gocryptotrader/blob/engine/engine/engine.go

I think the makefile changes, spelling mistake fixes and the improvements you've done with the bot struct member variables are great (dryrun, forex vars etc) and should be included. However, the moving of a lot of the start-up logic into their own funcs will double up on the work done and don't require to be exported, so I'm of the opinion that those specific changes should be reverted. 

This also highlights the need for documentation for devs on how the bot starts up, what systems are involved and how to change its behaviour as desired.

**Comment by lukekhamilton** [comment]
Hey @dfischer , thanks for the link. Super interesting read. As someone that trying to get into this codebase and following the layout of how main() was I personally found it to be very inconsistent in its style and also overly complicated to just try and quickly work out what was getting fired up, and the why. Now I also don't think this is the best approach as a number of the function all follow slightly different styles, especially when it comes to the firing up of goroutines.

What I think would be great is a conversation about how we/this project would like to make areas of the codebase clearer, less complicated, less over-engineered?  

Love to hear what suggests you have in this area @dfischer and others?

**Comment by lukekhamilton** [comment]
Hey, @thrasher- didn't see your message before I posted that last message. Just had a look at these changes and they are great. This is a much better pattern. What's your timing on having this branch merged into master? If it's soon ill just wait. Am keen to get involved however, I can see so much is changed in the engine branch it makes it hard to do anything that won't double up.

**Pull request closed without merging**
