### PR TITLE
Add Kline Extension

### PR DESCRIPTION
**Pull request by idoall**
# Description

Extension refers to the function of obtaining candle data

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Please also consider improving test coverage whilst working on a certain package

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool 
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Travis with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by thrasher-** [comment]
Thanks @idoall! I've made a branch of this and will fix up some things before it can me merged into master. You can track it here: https://github.com/thrasher-/gocryptotrader/tree/idoall_progress

**Comment by thrasher-** [comment]
I'll close this one for now.

**Comment by idoall** [comment]
Thank you very much for changing the namespace reference package because I have my own needs. Now that you have a comprehensive function, only one candle line is missing, I have expanded the implementation of the Binance. I hope it will help you and others.
Earlier last year, I also submitted Gate. IO and ZB's exchange API. Can I add my code repository to the list of contributors?

**Comment by thrasher-** [comment]
Sorry for the late reply @idoall, I've been away for the past month. It is absolutely fine to add you to the list of contributors! Thanks again for your contributions

**Pull request closed without merging**
