### PR TITLE
Big

### PR DESCRIPTION
**Pull request by idoall**
+ 简单一些操作
+ 修复火币在 Post 时的bug，同时增加 HuobiHadax 的支持
+ 修复 Binance 获取用户信息的bug,增加 Binance 取消订单的方法，获取订单状态，获取所有打开的状态以及所有订单
+ 增加 Gateio 交易所的支持，支持获取K线、支持的交易对、交易市场参数、买/卖订单、取消订单
+ OKEX 币币交易:增加获取用户信息，下订单，取消订单
+ 修复 Bitfinex 的 GetAccountInfo 方法
+ 增加 ZB 交易所的部分功能支持

### CODE REVIEW

**Comment by thrasher-** [comment]
Thanks for the PR but was this opened in error? There's merge conflicts which require fixing and there's a lot of import updates which point away from this repo.

**Comment by thrasher-** [comment]
谢谢你的PR。 它是一组很棒的功能，增加了一些非常理想的交换。 合并冲突问题现已修复，但仍存在一些问题：

1）一些进口指向碘回购
2）main.go被自定义代码覆盖

如果您愿意，我很乐意解决这些错误。

请原谅这个翻译，你有没有机会在GoCryptoTrader上懈怠？ 或者你使用微信？

**Comment by idoall** [comment]
Hello, thank you for providing this public library, which is very helpful to me.



Because of my personalized needs, there are more personalized code to modify, and there is no way to maintain the original function.

I'll probably continue to personalize my needs, modify the code, and then send you, you can have the choice to merge into the trunk, and I'll be as much as possible to be compatible with the previous code base:)

wechat:ian_sky

**Comment by thrasher-** [comment]
Thanks for your reply! Glad it is useful for you. I'll start merging in the applicable code :)

**Comment by thrasher-** [comment]
Thanks again, the code has been merged in. Note: Soon there will be a way to get a default config for all exchanges like what you've done which will make the functionality a lot better.

**Pull request closed without merging**
